### ISSUE TITLE
Add nextjs

### ISSUE THREAD

**Issue by Geczy** [coderboxapp/react-mobx-starter-kit#1]
Saw you mention this at arc repo

Can you even add next to it?

**Comment by Geczy** [comment]
Maybe new branch

**Comment by ghalex** [comment]
You can easily add next.js to this, check this repository:
https://github.com/ghalex/phimail

**Comment by Geczy** [comment]
Nice! Thanks

ALt question

https://github.com/ghalex/phimail/blob/master/templates/index.js

What is the benefit of including each file manually? Or do you have an automatic process for this?

**Comment by ghalex** [comment]
There are some drawbacks of using require.context. You can read here more about that here:
https://github.com/diegohaz/arc/issues/131#issuecomment-314497638
